export class CCS_Inward{
    date : Date;
    cpn : string;
    contract_no : string;
    business_id : string;
    drawee_bank : string;
    type : string;
    benificiary_acc : string;
    benificiary_name : string;
    remittee_acc : string;
    remittee_name : string;
    fee_amt : number;
    commission_amt : number;
    cash_amt : number;
    transfer_amt : number;
    total_amt : number;
    status : string;
    remark : string;
}